import { createApp } from "vue";
import App from "./App.vue";
import router from "./router/index";
import uiComponents from "./ui-components";
import store from "./store";
const app = createApp(App);
uiComponents.map((comp) => app.component(comp.name, comp));
app.use(router);
app.use(store);
app.mount("#app");
